import type { EquityMarketConfig } from "./types";

/** Country / index registry — keep map UI free of hardcoded market logic. */
export const EQUITY_MARKETS: readonly EquityMarketConfig[] = [
  {
    countryId: "US",
    countryName: "United States",
    iso2: "US",
    iso3: "USA",
    isoNumeric: "840",
    region: "North America",
    indexName: "S&P 500",
    ticker: "^GSPC",
    source: "Yahoo Finance",
    isLive: true,
    overviewQuoteLabel: "S&P 500",
  },
  {
    countryId: "SE",
    countryName: "Sweden",
    iso2: "SE",
    iso3: "SWE",
    isoNumeric: "752",
    region: "Europe",
    indexName: "OMXS30",
    ticker: "^OMX",
    source: "Yahoo Finance",
    isLive: true,
    overviewQuoteLabel: "OMX Stockholm 30",
  },
  {
    countryId: "DE",
    countryName: "Germany",
    iso2: "DE",
    iso3: "DEU",
    isoNumeric: "276",
    region: "Europe",
    indexName: "DAX",
    ticker: "^GDAXI",
    source: "Yahoo Finance",
    isLive: true,
  },
  {
    countryId: "FR",
    countryName: "France",
    iso2: "FR",
    iso3: "FRA",
    isoNumeric: "250",
    region: "Europe",
    indexName: "CAC 40",
    ticker: "^FCHI",
    source: "Yahoo Finance",
    isLive: true,
  },
  {
    countryId: "GB",
    countryName: "United Kingdom",
    iso2: "GB",
    iso3: "GBR",
    isoNumeric: "826",
    region: "Europe",
    indexName: "FTSE 100",
    ticker: "^FTSE",
    source: "Yahoo Finance",
    isLive: true,
  },
  {
    countryId: "JP",
    countryName: "Japan",
    iso2: "JP",
    iso3: "JPN",
    isoNumeric: "392",
    region: "Asia-Pacific",
    indexName: "Nikkei 225",
    ticker: "^N225",
    source: "Yahoo Finance",
    isLive: true,
  },
  {
    countryId: "CN",
    countryName: "China",
    iso2: "CN",
    iso3: "CHN",
    isoNumeric: "156",
    region: "Asia-Pacific",
    indexName: "CSI 300",
    ticker: "000300.SS",
    source: "Yahoo Finance",
    isLive: true,
  },
  {
    countryId: "HK",
    countryName: "Hong Kong",
    iso2: "HK",
    iso3: "HKG",
    isoNumeric: "344",
    region: "Asia-Pacific",
    indexName: "Hang Seng",
    ticker: "^HSI",
    source: "Yahoo Finance",
    isLive: true,
  },
  {
    countryId: "IN",
    countryName: "India",
    iso2: "IN",
    iso3: "IND",
    isoNumeric: "356",
    region: "Asia-Pacific",
    indexName: "Nifty 50",
    ticker: "^NSEI",
    source: "Yahoo Finance",
    isLive: true,
  },
  {
    countryId: "KR",
    countryName: "South Korea",
    iso2: "KR",
    iso3: "KOR",
    isoNumeric: "410",
    region: "Asia-Pacific",
    indexName: "KOSPI",
    ticker: "^KS11",
    source: "Yahoo Finance",
    isLive: true,
  },
  {
    countryId: "AU",
    countryName: "Australia",
    iso2: "AU",
    iso3: "AUS",
    isoNumeric: "036",
    region: "Asia-Pacific",
    indexName: "ASX 200",
    ticker: "^AXJO",
    source: "Yahoo Finance",
    isLive: true,
  },
  {
    countryId: "CA",
    countryName: "Canada",
    iso2: "CA",
    iso3: "CAN",
    isoNumeric: "124",
    region: "North America",
    indexName: "TSX",
    ticker: "^GSPTSE",
    source: "Yahoo Finance",
    isLive: true,
  },
  {
    countryId: "BR",
    countryName: "Brazil",
    iso2: "BR",
    iso3: "BRA",
    isoNumeric: "076",
    region: "Latin America",
    indexName: "Bovespa",
    ticker: "^BVSP",
    source: "Yahoo Finance",
    isLive: true,
  },
  {
    countryId: "MX",
    countryName: "Mexico",
    iso2: "MX",
    iso3: "MEX",
    isoNumeric: "484",
    region: "Latin America",
    indexName: "IPC",
    ticker: "^MXX",
    source: "Yahoo Finance",
    isLive: true,
  },
  {
    countryId: "IT",
    countryName: "Italy",
    iso2: "IT",
    iso3: "ITA",
    isoNumeric: "380",
    region: "Europe",
    indexName: "FTSE MIB",
    ticker: "FTSEMIB.MI",
    source: "Yahoo Finance",
    isLive: true,
  },
  {
    countryId: "ES",
    countryName: "Spain",
    iso2: "ES",
    iso3: "ESP",
    isoNumeric: "724",
    region: "Europe",
    indexName: "IBEX 35",
    ticker: "^IBEX",
    source: "Yahoo Finance",
    isLive: true,
  },
  {
    countryId: "NL",
    countryName: "Netherlands",
    iso2: "NL",
    iso3: "NLD",
    isoNumeric: "528",
    region: "Europe",
    indexName: "AEX",
    ticker: "^AEX",
    source: "Yahoo Finance",
    isLive: true,
  },
  {
    countryId: "CH",
    countryName: "Switzerland",
    iso2: "CH",
    iso3: "CHE",
    isoNumeric: "756",
    region: "Europe",
    indexName: "SMI",
    ticker: "^SSMI",
    source: "Yahoo Finance",
    isLive: true,
  },
  {
    countryId: "NO",
    countryName: "Norway",
    iso2: "NO",
    iso3: "NOR",
    isoNumeric: "578",
    region: "Europe",
    indexName: "OBX",
    ticker: "OSEBX.OL",
    source: "Yahoo Finance",
    isLive: true,
  },
  {
    countryId: "DK",
    countryName: "Denmark",
    iso2: "DK",
    iso3: "DNK",
    isoNumeric: "208",
    region: "Europe",
    indexName: "OMX Copenhagen 25",
    ticker: "^OMXC25",
    source: "Yahoo Finance",
    isLive: true,
  },
  {
    countryId: "FI",
    countryName: "Finland",
    iso2: "FI",
    iso3: "FIN",
    isoNumeric: "246",
    region: "Europe",
    indexName: "OMX Helsinki 25",
    ticker: "^OMXH25",
    source: "Yahoo Finance",
    isLive: true,
  },
  {
    countryId: "omxn40",
    countryName: "Nordics",
    iso2: "",
    iso3: "",
    isoNumeric: "",
    region: "Europe",
    indexName: "OMXN40",
    ticker: "^OMXN40",
    source: "Yahoo Finance",
    isLive: true,
  },
  {
    countryId: "eu500",
    countryName: "Europe",
    iso2: "",
    iso3: "",
    isoNumeric: "",
    region: "Europe",
    indexName: "EU500",
    ticker: "EU500.AS",
    source: "Yahoo Finance",
    isLive: true,
  },
  {
    countryId: "nqgi",
    countryName: "Global",
    iso2: "",
    iso3: "",
    isoNumeric: "",
    region: "Global",
    indexName: "Nasdaq Global",
    ticker: "^NQGI",
    source: "Avanza",
    isLive: true,
  },
  {
    countryId: "ZA",
    countryName: "South Africa",
    iso2: "ZA",
    iso3: "ZAF",
    isoNumeric: "710",
    region: "Africa",
    indexName: "NQZA",
    ticker: "^NQZA",
    source: "Yahoo Finance",
    isLive: true,
  },
] as const;

export const EQUITY_MARKET_BY_ID = Object.fromEntries(
  EQUITY_MARKETS.map((m) => [m.countryId, m]),
) as Record<string, EquityMarketConfig>;

export const EQUITY_MARKET_BY_ISO_NUMERIC = Object.fromEntries(
  EQUITY_MARKETS.filter((m) => m.isoNumeric.length > 0).map((m) => [m.isoNumeric, m]),
) as Record<string, EquityMarketConfig>;
