/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YieldCurvesRouteImport } from './routes/yield-curves'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as MorningBriefRouteImport } from './routes/morning-brief'
import { Route as ForeignExchangeRouteImport } from './routes/foreign-exchange'
import { Route as EquitiesRouteImport } from './routes/equities'
import { Route as EmergingMarketsRouteImport } from './routes/emerging-markets'
import { Route as DerivativesRouteImport } from './routes/derivatives'
import { Route as IndexRouteImport } from './routes/index'

const YieldCurvesRoute = YieldCurvesRouteImport.update({
  id: '/yield-curves',
  path: '/yield-curves',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const MorningBriefRoute = MorningBriefRouteImport.update({
  id: '/morning-brief',
  path: '/morning-brief',
  getParentRoute: () => rootRouteImport,
} as any)
const ForeignExchangeRoute = ForeignExchangeRouteImport.update({
  id: '/foreign-exchange',
  path: '/foreign-exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const EquitiesRoute = EquitiesRouteImport.update({
  id: '/equities',
  path: '/equities',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergingMarketsRoute = EmergingMarketsRouteImport.update({
  id: '/emerging-markets',
  path: '/emerging-markets',
  getParentRoute: () => rootRouteImport,
} as any)
const DerivativesRoute = DerivativesRouteImport.update({
  id: '/derivatives',
  path: '/derivatives',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/derivatives': typeof DerivativesRoute
  '/emerging-markets': typeof EmergingMarketsRoute
  '/equities': typeof EquitiesRoute
  '/foreign-exchange': typeof ForeignExchangeRoute
  '/morning-brief': typeof MorningBriefRoute
  '/watchlist': typeof WatchlistRoute
  '/yield-curves': typeof YieldCurvesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/derivatives': typeof DerivativesRoute
  '/emerging-markets': typeof EmergingMarketsRoute
  '/equities': typeof EquitiesRoute
  '/foreign-exchange': typeof ForeignExchangeRoute
  '/morning-brief': typeof MorningBriefRoute
  '/watchlist': typeof WatchlistRoute
  '/yield-curves': typeof YieldCurvesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/derivatives': typeof DerivativesRoute
  '/emerging-markets': typeof EmergingMarketsRoute
  '/equities': typeof EquitiesRoute
  '/foreign-exchange': typeof ForeignExchangeRoute
  '/morning-brief': typeof MorningBriefRoute
  '/watchlist': typeof WatchlistRoute
  '/yield-curves': typeof YieldCurvesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/derivatives'
    | '/emerging-markets'
    | '/equities'
    | '/foreign-exchange'
    | '/morning-brief'
    | '/watchlist'
    | '/yield-curves'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/derivatives'
    | '/emerging-markets'
    | '/equities'
    | '/foreign-exchange'
    | '/morning-brief'
    | '/watchlist'
    | '/yield-curves'
  id:
    | '__root__'
    | '/'
    | '/derivatives'
    | '/emerging-markets'
    | '/equities'
    | '/foreign-exchange'
    | '/morning-brief'
    | '/watchlist'
    | '/yield-curves'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DerivativesRoute: typeof DerivativesRoute
  EmergingMarketsRoute: typeof EmergingMarketsRoute
  EquitiesRoute: typeof EquitiesRoute
  ForeignExchangeRoute: typeof ForeignExchangeRoute
  MorningBriefRoute: typeof MorningBriefRoute
  WatchlistRoute: typeof WatchlistRoute
  YieldCurvesRoute: typeof YieldCurvesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yield-curves': {
      id: '/yield-curves'
      path: '/yield-curves'
      fullPath: '/yield-curves'
      preLoaderRoute: typeof YieldCurvesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/morning-brief': {
      id: '/morning-brief'
      path: '/morning-brief'
      fullPath: '/morning-brief'
      preLoaderRoute: typeof MorningBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foreign-exchange': {
      id: '/foreign-exchange'
      path: '/foreign-exchange'
      fullPath: '/foreign-exchange'
      preLoaderRoute: typeof ForeignExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equities': {
      id: '/equities'
      path: '/equities'
      fullPath: '/equities'
      preLoaderRoute: typeof EquitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emerging-markets': {
      id: '/emerging-markets'
      path: '/emerging-markets'
      fullPath: '/emerging-markets'
      preLoaderRoute: typeof EmergingMarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/derivatives': {
      id: '/derivatives'
      path: '/derivatives'
      fullPath: '/derivatives'
      preLoaderRoute: typeof DerivativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DerivativesRoute: DerivativesRoute,
  EmergingMarketsRoute: EmergingMarketsRoute,
  EquitiesRoute: EquitiesRoute,
  ForeignExchangeRoute: ForeignExchangeRoute,
  MorningBriefRoute: MorningBriefRoute,
  WatchlistRoute: WatchlistRoute,
  YieldCurvesRoute: YieldCurvesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
